<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMxpshjm\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMxpshjm/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerMxpshjm.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerMxpshjm\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerMxpshjm\appProdProjectContainer(array(
    'container.build_hash' => 'Mxpshjm',
    'container.build_id' => 'da33d101',
    'container.build_time' => 1538930728,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerMxpshjm');
