<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRr8pvpz\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRr8pvpz/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerRr8pvpz.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerRr8pvpz\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerRr8pvpz\appProdProjectContainer(array(
    'container.build_hash' => 'Rr8pvpz',
    'container.build_id' => '5c670df2',
    'container.build_time' => 1540108510,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerRr8pvpz');
